### PR TITLE
End to end testing

### PR DESCRIPTION
**Pull request by philipqueen**
This PR adds end to end testing of the core software pipeline. It downloads synchronized videos and a calibration toml file, processes them through freemocap, and then verifies the shapes of all of the created files.

Currently it processes the data headless, in that the gui frontend is not used. A future improvement will be to implement end to end testing that verifies that the gui works properly as well.

### CODE REVIEW

**Comment by philipqueen** [comment]
@jonmatthis this is running smooth on my machine, and is ready for review. It takes about 1 minute 45 seconds to download the data, process it in freemocap, and run the tests.

**Comment by philipqueen** [comment]
I've placed all of the setup code in `conftest.py` in a `pytest_sessionstart` hook, which is run at the start of the pytest session. This seems to be the preferred way of configuring global variables.

Here's the explanation of conftest: https://docs.pytest.org/en/latest/reference/fixtures.html#conftest-py-sharing-fixtures-across-multiple-files

and the session start hook:
https://docs.pytest.org/en/latest/reference/reference.html#pytest.hookspec.pytest_sessionstart

**Comment by jonmatthis** [comment]
let's use `image_tracking_data` kinds of language for the data that comes out of whatever image tracking method we use, and keep `skeleton_data` kinds of language to mean the data that we have cleaned up for you to use as mocap data

**Comment by philipqueen** [comment]
copy that @Jon, I've made that change, and this should be ready for final review

**Comment by jonmatthis** [comment]
@aaroncherian - please double check you can get a recording to run with this branch using webcams and whatnot

**Review by aaroncherian — APPROVED** [review]
- [x ] Single camera recording successful  

- [x] Multi camera recording successful 

- [x] Pytest passes (note: need to use `pytest freemocap/tests` after navigating to the freemocap folder in the terminal)

**Comment by jonmatthis** [comment]
Hey, I tried to run it on my end and it looks like its not downloading the sample data properly. Any ideas what might be going wrong? 

results of running `pytest`
```
(venv) PS C:\Users\jonma\github_repos\freemocap_organization\freemocap> pytest
========================================================================================================= test session starts =========================================================================================================
platform win32 -- Python 3.9.13, pytest-7.3.1, pluggy-1.0.0
rootdir: C:\Users\jonma\github_repos\freemocap_organization\freemocap
collecting ... adding base_package_path: C:\Users\jonma\github_repos\freemocap_organization\freemocap : to sys.path
adding base_package_path: C:\Users\jonma\github_repos\freemocap_organization\freemocap\venv\lib\site-packages\skellycam : to sys.path
Setting up skellycam logging C:\Users\jonma\github_repos\freemocap_organization\freemocap\venv\lib\site-packages\skellycam\system\log_config\logsetup.py
collected 4 items                                                                                                                                                                                                                      

freemocap\tests\test_image_tracking_data_shape.py E                                                                                                                                                                              [ 25%]
freemocap\tests\test_mediapipe_skeleton_data_shape.py E                                                                                                                                                                          [ 50%] 
freemocap\tests\test_synchronized_video_frame_counts.py E                                                                                                                                                                        [ 75%] 
freemocap\tests\test_total_body_center_of_mass_data_shape.py E                                                                                                                                                                   [100%]

=============================================================================================================== ERRORS ================================================================================================================ 
__________________________________________________________________________________________ ERROR at setup of test_image_tracking_data_shape ___________________________________________________________________________________________ 

    @pytest.fixture
    def synchronized_video_folder_path():
>       return find_synchronized_videos_folder_path(pytest.sample_session_folder_path)

freemocap\tests\conftest.py:31:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

name = 'sample_session_folder_path'

    def __getattr__(name: str) -> object:
        if name == "Instance":
            # The import emits a deprecation warning.
            from _pytest.python import Instance

            return Instance
>       raise AttributeError(f"module {__name__} has no attribute {name}")
E       AttributeError: module pytest has no attribute sample_session_folder_path

venv\lib\site-packages\pytest\__init__.py:169: AttributeError
________________________________________________________________________________________ ERROR at setup of test_mediapipe_skeleton_data_shape _________________________________________________________________________________________ 

    @pytest.fixture
    def synchronized_video_folder_path():
>       return find_synchronized_videos_folder_path(pytest.sample_session_folder_path)

freemocap\tests\conftest.py:31:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

name = 'sample_session_folder_path'

    def __getattr__(name: str) -> object:
        if name == "Instance":
            # The import emits a deprecation warning.
            from _pytest.python import Instance

            return Instance
>       raise AttributeError(f"module {__name__} has no attribute {name}")
E       AttributeError: module pytest has no attribute sample_session_folder_path

venv\lib\site-packages\pytest\__init__.py:169: AttributeError
_______________________________________________________________________________________ ERROR at setup of test_synchronized_video_frame_counts ________________________________________________________________________________________ 

    @pytest.fixture
    def synchronized_video_folder_path():
>       return find_synchronized_videos_folder_path(pytest.sample_session_folder_path)

freemocap\tests\conftest.py:31:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

name = 'sample_session_folder_path'

    def __getattr__(name: str) -> object:
        if name == "Instance":
            # The import emits a deprecation warning.
            from _pytest.python import Instance

            return Instance
>       raise AttributeError(f"module {__name__} has no attribute {name}")
E       AttributeError: module pytest has no attribute sample_session_folder_path

venv\lib\site-packages\pytest\__init__.py:169: AttributeError
_____________________________________________________________________________________ ERROR at setup of test_total_body_center_of_mass_data_shape _____________________________________________________________________________________ 

    @pytest.fixture
    def synchronized_video_folder_path():
>       return find_synchronized_videos_folder_path(pytest.sample_session_folder_path)

freemocap\tests\conftest.py:31:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

name = 'sample_session_folder_path'

    def __getattr__(name: str) -> object:
        if name == "Instance":
            # The import emits a deprecation warning.
            from _pytest.python import Instance

            return Instance
>       raise AttributeError(f"module {__name__} has no attribute {name}")
E       AttributeError: module pytest has no attribute sample_session_folder_path

venv\lib\site-packages\pytest\__init__.py:169: AttributeError
======================================================================================================= short test summary info ======================================================================================================= 
ERROR freemocap/tests/test_image_tracking_data_shape.py::test_image_tracking_data_shape - AttributeError: module pytest has no attribute sample_session_folder_path
ERROR freemocap/tests/test_mediapipe_skeleton_data_shape.py::test_mediapipe_skeleton_data_shape - AttributeError: module pytest has no attribute sample_session_folder_path
ERROR freemocap/tests/test_synchronized_video_frame_counts.py::test_synchronized_video_frame_counts - AttributeError: module pytest has no attribute sample_session_folder_path
ERROR freemocap/tests/test_total_body_center_of_mass_data_shape.py::test_total_body_center_of_mass_data_shape - AttributeError: module pytest has no attribute sample_session_folder_path
========================================================================================================== 4 errors in 2.35s ========================================================================================================== 
(venv) PS C:\Users\jonma\github_repos\freemocap_organization\freemocap> 
```

**Comment by philipqueen** [comment]
@jonmatthis you have to run `pytest freemocap/tests`

**Comment by jonmatthis** [comment]
Got another error: 


```python
(base) (venv) PS C:\Users\jonma\github_repos\freemocap_organization\freemocap> pytest freemocap/tests
============================================================================================================== test session starts ==============================================================================================================
platform win32 -- Python 3.10.2, pytest-7.3.0, pluggy-1.0.0
rootdir: C:\Users\jonma\github_repos\freemocap_organization\freemocap
collected 5 items                                                                                                                                                                                                                                

freemocap\tests\test_mediapipe_2d_data_shape.py E                                                                                                                                                                                          [ 20%]
freemocap\tests\test_mediapipe_3d_data_shape.py E                                                                                                                                                                                          [ 40%]
freemocap\tests\test_synchronized_video_frame_counts.py E                                                                                                                                                                                  [ 60%]
freemocap\tests\test_test.py .                                                                                                                                                                                                             [ 80%]
freemocap\tests\test_total_body_center_of_mass_data_shape.py E                                                                                                                                                                             [100%]

==================================================================================================================== ERRORS =====================================================================================================================
________________________________________________________________________________________________ ERROR at setup of test_mediapipe_2d_data_shape _________________________________________________________________________________________________
file C:\Users\jonma\github_repos\freemocap_organization\freemocap\freemocap\tests\test_mediapipe_2d_data_shape.py, line 12
  def test_mediapipe_2d_data_shape(
E       fixture 'synchronized_videos_folder' not found
>       available fixtures: cache, capfd, capfdbinary, caplog, capsys, capsysbinary, doctest_namespace, monkeypatch, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory
>       use 'pytest --fixtures [testpath]' for help on them.

C:\Users\jonma\github_repos\freemocap_organization\freemocap\freemocap\tests\test_mediapipe_2d_data_shape.py:12
________________________________________________________________________________________________ ERROR at setup of test_mediapipe_3d_data_shape _________________________________________________________________________________________________
file C:\Users\jonma\github_repos\freemocap_organization\freemocap\freemocap\tests\test_mediapipe_3d_data_shape.py, line 11
  def test_mediapipe_3d_data_shape(
E       fixture 'synchronized_videos_folder' not found
>       available fixtures: cache, capfd, capfdbinary, caplog, capsys, capsysbinary, doctest_namespace, monkeypatch, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory
>       use 'pytest --fixtures [testpath]' for help on them.

C:\Users\jonma\github_repos\freemocap_organization\freemocap\freemocap\tests\test_mediapipe_3d_data_shape.py:11
____________________________________________________________________________________________ ERROR at setup of test_synchronized_video_frame_counts _____________________________________________________________________________________________
file C:\Users\jonma\github_repos\freemocap_organization\freemocap\freemocap\tests\test_synchronized_video_frame_counts.py, line 10
  def test_synchronized_video_frame_counts(video_folder_path: Union[Path, str]):
E       fixture 'video_folder_path' not found
>       available fixtures: cache, capfd, capfdbinary, caplog, capsys, capsysbinary, doctest_namespace, monkeypatch, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory
>       use 'pytest --fixtures [testpath]' for help on them.

C:\Users\jonma\github_repos\freemocap_organization\freemocap\freemocap\tests\test_synchronized_video_frame_counts.py:10
__________________________________________________________________________________________ ERROR at setup of test_total_body_center_of_mass_data_shape __________________________________________________________________________________________
file C:\Users\jonma\github_repos\freemocap_organization\freemocap\freemocap\tests\test_total_body_center_of_mass_data_shape.py, line 11
  def test_total_body_center_of_mass_data_shape(
E       fixture 'synchronized_videos_folder' not found
>       available fixtures: cache, capfd, capfdbinary, caplog, capsys, capsysbinary, doctest_namespace, monkeypatch, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory
>       use 'pytest --fixtures [testpath]' for help on them.

C:\Users\jonma\github_repos\freemocap_organization\freemocap\freemocap\tests\test_total_body_center_of_mass_data_shape.py:11
============================================================================================================ short test summary info ============================================================================================================
ERROR freemocap/tests/test_mediapipe_2d_data_shape.py::test_mediapipe_2d_data_shape
ERROR freemocap/tests/test_mediapipe_3d_data_shape.py::test_mediapipe_3d_data_shape
ERROR freemocap/tests/test_synchronized_video_frame_counts.py::test_synchronized_video_frame_counts
ERROR freemocap/tests/test_total_body_center_of_mass_data_shape.py::test_total_body_center_of_mass_data_shape
========================================================================================================== 1 passed, 4 errors in 0.20s ========================================================================================================== 
```
(base) (venv) PS C:\Users\jonma\github_repos\freemocap_organization\freemocap>

**Comment by philipqueen** [comment]
@jonmatthis is your branch up to date? Pytest is collecting a test_test file that was deleted in this branch

**Comment by philipqueen** [comment]
FWIW, if you have trouble with import statements (i.e. module not found errors when importing from within freemocap) using `pytest freemocap/tests`, using `python -m pytest freemocap/tests` fixed them for me. For me some environments will work without the addition and some won't.

**Review by jonmatthis — APPROVED** [review]
Approved! Looks great! Thanks for the work on this :D

Also FYI - I went ahead and made those fixes to the "deprecated escape" whosits we can go ahead and close #396 I think

**Pull request merged**
