### PR TITLE
Philip/recoloring

### PR DESCRIPTION
**Pull request by philipqueen**
I've switched the pure white and pure black to more muted versions. I've also played around a bit with the button colors, some options are below with the hex codes visible in the "tag" field so we can tell them apart.
Screen Shot 2023-04-24 at 10 25 33 AM
Screen Shot 2023-04-24 at 10 24 41 AM
Screen Shot 2023-04-24 at 10 24 10 AM
Screen Shot 2023-04-24 at 10 23 44 AM
Screen Shot 2023-04-24 at 10 23 13 AM

### CODE REVIEW

**Comment by philipqueen** [comment]
I think I found a better button border, and also added some styling for clicked buttons:
Screen Shot 2023-05-02 at 12 36 42 PM

I also added explicit styling for the wizard elements so they mostly show up better:
Screen Shot 2023-05-02 at 12 40 48 PM

**Comment by philipqueen** [comment]
I've added different colors for primary (red) vs secondary (purple red) colors, which can be seen below. To change the detect available cameras button, it needs to have its name set in skellycam, which I've added a PR for.
Screen Shot 2023-05-10 at 10 37 25 AM
Screen Shot 2023-05-10 at 10 37 15 AM

**Comment by philipqueen** [comment]
I've added better contrast on disabled buttons. It nows passes the full WCAG AAA contrast test.

Screen Shot 2023-05-10 at 10 52 07 AM

**Comment by philipqueen** [comment]
It's easier at this point to do a full recoloring of the gui, so all of the button colors except for `process motion capture videos` have been reverted, and this PR is mostly just color contrast changes. Here's what it looks like now:

Screen Shot 2023-05-12 at 10 03 07 AM

**Review by jonmatthis — APPROVED** [review]

**Pull request merged**
