### PR TITLE
Add privacy policy link

### PR DESCRIPTION
**Pull request by philipqueen**
Adds a link to the privacy policy under the user pings checkbox and shortens the user pings text.

### CODE REVIEW

**Comment by trentwirth** [comment]
screenshot for posterity:
image
I think it looks great!

**Review by trentwirth — APPROVED** [review]
looks good, needs @jonmatthis 's approval now 🚀

**Comment by jonmatthis** [comment]
> screenshot for posterity: 😞 😢 

*screenshot because it's a necessary component of our agreed upon PR workflow 🤩 👍

**Review by jonmatthis — APPROVED** [review]
Looks great!

**Pull request merged**
